name: cml-ami
on: 
  push:
    tags:
      - 'ami*'

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Packer
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_INSTANCE_TYPE: g2.2xlarge
        run: |
          sudo apt install unzip

          cd packer
          packer validate ami.json
          packer build ami.json
          ./clone-amis.go
