name: cml-ami
on: 
  push:
    tags:
      - 'ami*'

jobs:
  build-ami:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['us-east-1', 'us-west-1', 'eu-west-1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Packer
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          sudo apt install unzip

          cd packer
          export AWS_REGION=${{ matrix.region }}
          packer validate ami.json
          packer build ami.json
