name: cml-ami
on: 
  push:
    tags:
      - 'ami*'

jobs:
  buiild-ami:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['us-east-1', 'us-west-1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Packer
        run: |
          apt install unzip

          # install packer
          export VER="1.5.6"
          wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
          unzip packer_${VER}_linux_amd64.zip
          mv packer /usr/local/bin

          cd packer
          export AWS_REGION={{ matrix.region }}
          packer validate ami.json
          packer build ami.json
